//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFerreteria_VENTAS_ALMACEN
{
    using System;
    using System.Collections.Generic;
    
    public partial class templeados
    {
        public templeados()
        {
            this.tcompras = new HashSet<tcompras>();
        }
    
        public string dni_empleado { get; set; }
        public string nombre_usuario { get; set; }
        public string nombre_empleado { get; set; }
        public string apellidos_empleado { get; set; }
        public System.DateTime nacimiento_empleado { get; set; }
    
        public virtual ICollection<tcompras> tcompras { get; set; }
        public virtual tusuarios tusuarios { get; set; }
    }
}
