//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFerreteria_VENTAS_ALMACEN
{
    using System;
    using System.Collections.Generic;
    
    public partial class tproductos
    {
        public tproductos()
        {
            this.tdetallecompras = new HashSet<tdetallecompras>();
            this.tsuministros = new HashSet<tsuministros>();
            this.tsuministrosempresas = new HashSet<tsuministrosempresas>();
        }
    
        public int codigo_producto { get; set; }
        public string descripcion_producto { get; set; }
        public float precio_producto { get; set; }
        public int existencias_producto { get; set; }
    
        public virtual tdescuentos tdescuentos { get; set; }
        public virtual ICollection<tdetallecompras> tdetallecompras { get; set; }
        public virtual ICollection<tsuministros> tsuministros { get; set; }
        public virtual ICollection<tsuministrosempresas> tsuministrosempresas { get; set; }
    }
}
