//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFerreteria_VENTAS_ALMACEN
{
    using System;
    using System.Collections.Generic;
    
    public partial class tusuarios
    {
        public tusuarios()
        {
            this.templeados = new HashSet<templeados>();
        }
    
        public string nombre_usuario { get; set; }
        public int Id_TipoUsuario { get; set; }
        public byte[] contrasenia_usuario { get; set; }
    
        public virtual ICollection<templeados> templeados { get; set; }
        public virtual ttipousuarios ttipousuarios { get; set; }
    }
}
